### PR TITLE
Added PlasmidID template

### PR DESCRIPTION
**Pull request by GuilleGorines**

### CODE REVIEW

**Comment by saramonzon** [comment]
Looks fine to me, but @svarona  please take a look. I think it is fine for now...once we figure how we can concatenate two templates we could remove assembly stuff from this one including that plasmidID has assembly as a "dependency"

**Comment by svarona** [comment]
El "template": "PlasmidID_assembly" del json de servicios se tiene que llamar igual que la carpeta, la A tiene que ser mayúscula en los dos lo minúscula en los dos

**Comment by svarona** [comment]
Y quita la carpeta work de delete_folders porque ahora en el clean se gestiona de otra manera @GuilleGorines

**Comment by GuilleGorines** [comment]
I'm positive everything has been taken care of! Please check it and I'll make the pertinent modifications

**Review by svarona — APPROVED** [review]

**Pull request merged**
